name: Sync Repository

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  push_to_another_repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Git
      run: |
        git config --global user.email "zeb.urrehman@hyfen.com" # $(git log -1 --pretty=format:'%ae')
        git config --global user.name "Zeb ur Rehman" # $(git log -1 --pretty=format:'%an')

    - name: Push Commits to Another Repository
      run: |
        :let SOURCE_REPO_URL="https://github.com/${{ github.repository }}"
        :let DEST_REPO_URL="https://github.com/zebhyfen/git-playground-copy.git"
        :let BRANCH_NAME="${{ github.ref }}"
        
        echo "Cloning the destination repository... $DEST_REPO_URL"
        git clone "$DEST_REPO_URL" destination_repo
        cd destination_repo

        echo "Checking out the branch... $BRANCH_NAME"
        git checkout -B "$BRANCH_NAME"

        echo "Fetching changes from the source repository... $SOURCE_REPO_URL"
        git fetch "$SOURCE_REPO_URL" "+refs/heads/*:refs/remotes/source/*"
        
        echo "Merging changes from the source repository... source/$BRANCH_NAME"
        git merge "source/main" --no-edit

        echo "$Remotes are "
        git remote -v
        
        echo "Pushing changes to the destination repository... $DEST_REPO_URL"
        git push "$DEST_REPO_URL" "main"

    # - name: Merge and Push the changes
    #   run: |
    #     SOURCE_REPO_URL="https://github.com/${{ github.repository }}"
    #     DEST_REPO_URL="https://github.com/zebhyfen/git-playground-copy.git"
    #     BRANCH_NAME="${{ github.ref }}"
        
    #     echo "Merging changes from the source repository... source/$BRANCH_NAME"
    #     git merge "source/main" --no-edit

        # echo "Pushing changes to the destination repository... $DEST_REPO_URL"
        # git push "$DEST_REPO_URL" "main"

      env:
        SOURCE_REPO_URL: ${{ github.event.repository.html_url }}
        DEST_REPO_URL: ${{ secrets.DEST_REPO_URL }}
